looker: remove complexity from image build (yarn.lock)
This was a PITA in the last 60 mins -- not sure why,
but I think the idea of using a massive yarn.lock
file and then installing only a subset is kind of
flawed. yarn did a huge removal on yarn.lock and
that failed the command. Want to keep the
independence, so no global yarn.lock for now.

Signed-off-by: Dr. Jan-Philip Gehrcke <jp@opstrace.com>

diff --git a/test/test-remote/looker/Dockerfile b/test/test-remote/looker/Dockerfile
--- a/test/test-remote/looker/Dockerfile
+++ b/test/test-remote/looker/Dockerfile
@@ -1,25 +1,16 @@
-FROM node:14-slim
+FROM node:14-slim AS build-stage
+
+# Copy just what's needed to install packages with yarn (invalidate this cache
+# layer only when one of these files change). For now, do not use a yarn.lock
+# file: had the challenge to use repo-wide yarn.lock file during the rather
+# independent build, and with --frozen-lockfile the install then failed with
+# a gazillion of _removals_ from yarn.lock
 RUN mkdir /build
-RUN mkdir /rundir
-RUN mkdir /lookerbin
-
-# Build context is the root directory in the repo. Pragmatically
-# cherry-pick what's required to quickly build looker.
-# Use a dedicated package.json/tsconfig.json for the Docker image build,
-# only use the root's `yarn.lock`.
-
-COPY yarn.lock /build
-# Copy looker sources into the image. This creates
-# /build/tsconfig.json and /build/package.json
-COPY ./package.json /build
-COPY ./tsconfig.json /build
+COPY tsconfig.json package.json /build/
 WORKDIR /build
 
-# Bake dependencies into the image, based on /build/looker/package.json and
-# /build/yarn.lock.
-RUN echo /build: && \
-    ls -al /build/* && \
-    yarn install --global --frozen-lockfile
+RUN echo /build: && ls -al /build/* && yarn install
+
 
 # Now copy in all other source files. And build
 # Could remove `tsc` after that to reduce imagesize (use layers)
@@ -29,12 +20,26 @@ COPY . /build
 RUN find . | grep -v node_modules | sed -e "s/[^-][^\/]*\// |/g" -e "s/|\([^ ]\)/|-\1/"
 RUN yarn run tsc -b tsconfig.json
 
-#RUN echo "contents of _tscbuild:"
+
+# Second stage, lean image w/o build tooling.
+FROM node:14-slim AS prod-stage
+WORKDIR /build
+COPY tsconfig.json package.json /build/
+RUN yarn install --production
+
+# Copy the _tscbuild output directory from the previous build stage.
+COPY --from=build-stage /build/_tscbuild /build/_tscbuild
+#RUN cd /build && du -ha . | sort -r -h | head -n 50 || true
 
 # But 'executable' into PATH.
+RUN mkdir /lookerbin
+RUN mkdir /rundir
 ENV PATH="/lookerbin:${PATH}"
 RUN chmod ugo+x /build/_tscbuild/index.js
 RUN ln -s /build/_tscbuild/index.js /lookerbin/looker
+
+#RUN du -hs *
+#RUN cd node_modules && du -hs *
 
 # See if the looker path works (to fail the build if this does not).
 RUN looker -h
